# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6512a38028010a55ba5cc3f55c953e0dda4ddd1289ce95bca71135506366716d417205ce4c7d2f917c7a1ad5cccfa376043972e5f9a780e068c3cb2e9bae8c06

test:
  secret_key_base: 6a774de94d29282fb94d814aa73e392344ffd86bf43db53837de9f5c6c9d282588e7121e853e97d5d80be14ed01bedc543bce2a0d77fc4f5c6bc1c504d2a06a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
